apiVersion: v1
kind: ReplicaSet
metadata:
  name: rs
spec:
  replicas: 3
  selector:
    matchLables:
    kumar: manglam
  template:
    metadata:
      name: podkum
      lables:
        kumar: manglam
    spec:
      containers:
        - name: c00
          image: ubuntu
          command: ["/bin/bash","-c","while true; do echo $kumar; sleep 5; done"]
        - name: c002
          image: nginx
          port:
            - containerPort: 80
